backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "media/images/tonypics" # Media files will be stored in the repo under images/uploads  
public_folder: "/media/images/tonypics"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/2-blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Published", name: "Published", widget: "datetime"}
      - {label: "Author", name: "Author", widget: "string"}
      - {label: "Template", widget: "hidden", default: "blog"}
      - {label: "Tag", name: "Tag", widget: "string"}
      - {label: "Body", name: "Body", widget: "markdown"}